<a href="https://colab.research.google.com/github/JUKYUNGYOO/image/blob/master/numpy_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
array = np.random.randint(1,10,size=4).reshape(2,2)
print(array)

[[4 4]
 [7 1]]


In [0]:
result_array = array * 10
print(result_array)

[[40 40]
 [70 10]]


In [0]:
import numpy as np
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)
array3 = array1 + array2
print(array3)

[[0 2]
 [2 4]]


In [0]:
import numpy as np 
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis = 0)
array4 = np.arange(0,4).reshape(4,1) #4*1


print(array3)


[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [0]:
import numpy as np
# 마스킹 연산 
array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 < 10
print(array2)

# 10보다 작은 원소를 선택해서 그 원소를 100 으로 바꾸어줌 

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [0]:
# numpy 집계함수 
import numpy as np 
array = np.arange(16).reshape(4,4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:",np.mean(array))

# 특정한 열에 대한 합계 출력

print("합계:",np.sum(array,axis = 0))



최대값: 15
최소값: 0
합계: 120
평균값: 7.5
합계: [24 28 32 36]
